import { Link } from '@tanstack/react-router';
import { Sprout, ArrowUpRight, Languages, Menu, ShieldCheck, Leaf } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Sheet,SheetContent,SheetTrigger,SheetTitle,SheetClose } from '@/components/ui/sheet';
import { useLanguage, type Language } from '@/lib/i18n';
export function Brand({small=false}:{small?:boolean}) {return <Link to="/" className={`brand ${small?'footer-brand':''}`}><span className="brand-icon"><Sprout size={23}/></span><span>AgroVision <span className="brand-ai">AI</span></span></Link>}
const nav=[['/','home'],['/detect','detect'],['/history','history'],['/about','about']] as const;
export function Header(){const {t,language,setLanguage}=useLanguage();return <header className="site-header"><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([to,key])=><Link key={to} to={to} activeOptions={{exact:true}} className="nav-link">{t(key)}</Link>)}</nav><div className="header-actions"><Select value={language} onValueChange={v=>setLanguage(v as Language)}><SelectTrigger aria-label="Language" className="language-trigger w-[119px] h-9 text-xs border-border"><Languages size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="en">English</SelectItem><SelectItem value="hi">हिंदी</SelectItem><SelectItem value="mr">मराठी</SelectItem></SelectContent></Select><Button asChild className="header-cta"><Link to="/detect">{t(startKey)}<ArrowUpRight/></Link></Button><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="mobile-menu" aria-label={t('menu')}><Menu/></Button></SheetTrigger><SheetContent><SheetTitle>AgroVision AI</SheetTitle><nav className="flex flex-col gap-2 mt-7">{nav.map(([to,key])=><SheetClose asChild key={to}><Button variant="ghost" asChild className="justify-start"><Link to={to}>{t(key)}</Link></Button></SheetClose>)}</nav></SheetContent></Sheet></div></div></header>}
const startKey='start';
export function Footer(){const {t}=useLanguage();return <footer className="site-footer"><div className="container"><div className="footer-top"><Brand small/><p className="text-xs text-muted-foreground">{t('footerLine')}</p><span className="text-xs text-muted-foreground">© 2026 AgroVision AI</span></div><div className="disclaimer"><ShieldCheck className="shrink-0 mt-0.5" size={16}/><p>{t('disclaimer')}</p></div></div></footer>}
export function DemoNotice(){const {t}=useLanguage();return <div className="demo-notice"><ShieldCheck size={18} className="shrink-0 mt-0.5"/><p>{t('demoNotice')}</p></div>}
export function PageHeading({title,description}:{title:'detect'|'history'|'about';description:'detectDesc'|'historyDesc'|'aboutDesc'}) {const {t}=useLanguage();return <div className="page-heading"><span className="eyebrow"><Leaf size={13}/>AgroVision AI</span><h1>{t(title)}</h1><p>{t(description)}</p></div>}
